spring.application.name=ecommerce-api

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${JWT_SECRET_GENERATOR_TOKEN}

logging.level.org.springframework.security=DEBUG

#Configuracoes de email.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}

spring.mail.password=${GOOGLE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:4200